library(devtools)
library(gsl)
devtools::install_github("mplatzer/BTYDplus", dependencies=TRUE)
library(BTYDplus)
demo(package="BTYDplus")
demo("cdnow")
demo("gg-nbd")
demo("mbg-cnbd-k")
demo("nbd")
demo("pareto-ggg")
demo("pareto-nbd-abe")
demo("timing")